apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: gcr.io/markuphero/webapp:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          resources:
            requests:
              cpu: "0.25"
              memory: "128Mi"
            limits:
              memory: "256Mi"
              cpu: "0.5"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: webapp

