<template>
  <div>
    <Nav></Nav>
    <div class="container">
      <h1>Privacy Policy</h1>
      <label>Updated March 25, 2020</label>
      <article>
        <p>HERO, Inc. ("Hero", “our”, “us” or “we”), respects your privacy and is committed to protecting it through our compliance with this privacy policy (“Privacy Policy”).</p>
        <p>Please read this Privacy Policy carefully to understand how Hero uses and protects the information that we collect from visitors to our website at markuphero.com, all other websites owned and operated by Hero that redirect to markuphero.com and all subdomains of markuphero.com (collectively, the “Hero Site”) the users (“Users”) of the Hero Properties (as defined below), and viewers of our Users’ content (“Viewers”).</p>
        <p>This Privacy Policy applies to information collected by Hero through the Hero Site, any Hero computer software downloadable or otherwise available from the Hero Site ("Hero Software") and any Hero services purchased or otherwise made available from the Hero Site ("Hero Services") (collectively, the "Hero Properties").This Privacy Policy does not apply to the practices of any third party websites, applications or services that Hero does not own or maintain (collectively, “Third Party Services”) or to any third parties that use the Hero Application Programming Interface (API) to perform any function related to the Hero Properties (“Integrated Platforms”). In particular, this Privacy Policy does not cover any information or other content you can view via the Hero Properties on Integrated Platforms or information you provide to Third Party Services accessed via the Hero Properties. As further detailed below, we cannot take responsibility for the content or privacy policies of any Third Party Services. If you are a Viewer we encourage you to carefully review the privacy policies of the Hero User whose Content you view and the privacy policies of any Integrated Platforms or Third Party Services used by such User which you may access via the Hero Properties.</p>
        <p>This Privacy Policy also does not cover any information, recorded in any form, about more than one individual where the identity of the individuals is not known and cannot be inferred from the information (“Aggregated Information”). Hero retains the right to use Aggregated Information in any way that it reasonably determines is appropriate.</p>
        <p>By using a Service or otherwise providing us with your Personal Information (as defined below), you are accepting the practices described in this Privacy Policy, as they may be amended by us from time to time, and agreeing to our collection and use of your information in accordance with this Privacy Policy. If you do not agree to the collection, use and disclosure of your information in this way, please do not use any of the Hero Properties or otherwise provide Hero with Personal Information.</p>
        <p>Please refer to our Privacy Overview at <a href="/privacy" v-on:click.prevent="redirectToPrivacy()">https://markuphero.com/privacy</a> for additional details regarding how Hero Properties may use your information, including Hero’s use of certain applications and platforms operated by Third Party Services, and how you may export your data.</p>
        <p><b>WHAT INFORMATION HERO COLLECTS FROM YOU</b><br>Hero collects only the information required to provide products and services to you. The amount of information provided by you and collected by Hero depends on the circumstances. Hero may collect two (2) types of information about you: Personal and Non-Personal.</p>
        <ol>
          <li>“Personal Information.” Personal Information means any information relating to an identified or identifiable individual. An identifiable individual is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that individual. Hero may collect Personal Information when you use the Hero Properties including, without limitation, setting up account information, filling out surveys, corresponding with Hero, or otherwise volunteering information about yourself.<br>
          </li>
          <li>“Non-Personal Information.” Non-Personal Information refers to information that, by itself, does not identify you as a specific individual (e.g. demographic information or website visitations). Hero may collect Non-Personal Information through any of the methods discussed above as well as automatically through use of industry standard technologies described further below.</li>
        </ol>
        <p><b>HOW HERO COLLECTS YOUR INFORMATION</b></p>
        <ol>
          <li>Registration. Prior to using one or more of the Hero Properties, Hero may require you to provide us with certain Personal Information and Non-Personal Information to create an account (“Account”) or to enable features or functionality of the Hero Properties.<br>
          </li>
          <li>Users. Hero may gather Personal Information about organizational representatives via various methods (phone, email, online forms, in-person meetings) but only if such Personal Information is submitted voluntarily. Hero may use such Personal Information for sales, marketing, and support of the Hero Properties. This Personal Information is never shared with third parties other than Third Party Service Providers utilized by a User in connection with Hero Services.<br>
          </li>
          <li>User communications. When you send email or other communications to us, we may retain those communications in order to process your inquiries, respond to your requests and improve the Hero Properties.<br>
          </li>
          <li>Payment Information. When creating an Account, for certain Hero Properties, or when you make online purchases, you may be asked to provide information, which may include your payment instrument number (e.g., credit card), your name and billing address, and the security code associated with your payment instrument (e.g., the CSV) and other financial data (“Payment Information”). We use Payment Information to complete transactions, as well as for the detection and prevention of fraud. When you provide Payment Information while authenticated, we will store that data to help you complete future transactions without your having to provide the information again. We do not, however, retain the security code associated with your payment instrument (e.g., the CSV) in this manner. To remove or modify Payment Information, please contact us. After you close your account or remove Payment Information, however, we may retain your Payment Information for as long as reasonably necessary to complete your existing transaction and for the detection and prevention at which point we will delete all of our Payment Information and Personal Information.Information Collected Through Technology. Hero automatically collects and receives certain information from your computer or mobile device, including the activities you perform on the Hero Site, the Hero Software and the Hero Services, the type of hardware and software you are using (for example, your operating system or browser), and information obtained from cookies (see below). If you have an Account, we may link this Non-Personal Information to your Account to better understand your needs and the needs of Users in the aggregate, diagnose problems, analyze trends, provide services, improve the features and usability of the Hero Properties, and better understand and market to our customers and Users.<br>
          </li>
          <li>We use technology to automatically gather information by the following methods:<br><br><i>Cookies</i>. Hero uses cookies on the Hero Site and other aspects of the Hero Properties. Cookies, including local shared objects, are small pieces of information that are stored by your browser on your computer's hard drive which work by assigning to your computer a unique number that has no meaning outside of the Hero Properties. Cookies do not generally contain any Personal Information. Most web browsers automatically accept cookies, but you can usually configure your browser to prevent this. Not accepting cookies may make certain features of the Hero Properties unavailable to you.<br><br><i>IP Address</i>. You may visit many areas of the Hero Site anonymously without the need to become a registered User. Even in such cases, Hero may collect IP addresses automatically. An IP address is a number that is automatically assigned to your computer whenever you begin services with an Internet services provider. Each time you access the Hero Site and each time you request one of the pages of the Hero Site, the server logs your IP address.<br><br><i>Web Beacons</i>. Web beacons are small pieces of data that are embedded in web pages and emails. Hero may use these technical methods in HTML emails that Hero sends to Users to determine whether they have opened those emails and/or clicked on links in those emails. The information from use of these technical methods may be collected in a form that is Personal Information.<br><br><i>Tracking Content Usage</i>. If you use the Hero Services and you post audio visual materials including, without limitation, videos, links, logos, artwork, graphics, pictures, advertisements, sound and other related intellectual property contained in such materials (collectively, “Content”) to your website or to a third party website, Hero tracks and captures Non-Personal Information associated with User accounts and the use of Content by those that access your Content.<br>
          </li>
          <li>Information You Provide About a Third Party. You may have the opportunity to communicate with others from the Hero Properties, such as by sending an invitation to a friend. If you choose to take advantage of this functionality, we may ask you to provide us with certain information about the person with whom you wish to communicate (e.g., name, email address, etc.). Hero collects such information for the purposes of facilitating the requested communication, which may contain a specific promotional message from you (e.g., an invitation to watch a video). Unless we explicitly say otherwise, Hero will not use this information for other marketing purposes without first obtaining consent from the person to whom the relevant information pertains. Please be aware that when you use any invitation functionality on the Hero Properties, your email address, name or username, and message may be included in the communication sent to your addressee(s).</li>
        </ol>
        <p>HOW HERO USES YOUR INFORMATION</p>
        <ol>
          <li>&nbsp;Personal Information. Hero identifies the purpose for which your Personal Information is collected and will be used or disclosed. If that purpose is not listed below, we will identify any additional purposes for which we will collect your Personal Information, before or at the time of collection, and we will obtain your consent to collect, use or disclose your Personal Information for such additional purpose(s).<br>
          </li>
          <li>By using the Hero Properties, you will be deemed to consent to our use of your Personal Information for the purposes of:<br><br>- communicating with you generally;<br>- processing your purchases;<br>- processing and keeping track of transactions and reporting back to you;<br>- protecting against fraud or error;<br>- providing information or services requested by you;<br>- administering and managing the Hero Properties and our business operations;<br>- personalizing your experience with the Hero Site, as well as evaluating statistics on Hero Site activity;<br>- performing statistical analyses of your behavior and characteristics, in order to measure interest in and use of the various sections of the Hero Site;<br>- communicating with you on other websites;<br>- email gating;<br>- delivery of content and information to Third Party Services Providers;<br>- complying with legal and governmental requirements; and/or<br>- fulfilling any other purpose that would be reasonably apparent to the average person at the time that we collect it.<br>
          </li>
          <li>Users utilize Hero Properties to manage and deliver Content to Viewers. As part of this process, Hero may collect Personal Information from you.<br>
          </li>
          <li>Otherwise, we will obtain your express consent (by verbal, written or electronic agreement) to collect, use or disclose your Personal Information. You can change your consent preferences at any time by contacting us (see the “How to Access, Change and Erase Your Personal Information” section below).<br>
          </li>
          <li>Hero extends the rights granted to “data subjects” under the General Data Protection Regulation (Regulation (EU) 2016/679) (the “GDPR”) to all of its Users. Consequently, you have the right to withdraw your consent to our processing of your Personal Information at any time (if our processing is based on consent) and the right to object to our processing of your Personal Information (if processing is based on legitimate interests).<br>
          </li>
          <li>Non-Personal Information. Hero may use Non-Personal Information for the following purposes:<br><br>- System Administration: Hero may use Non-Personal Information for the purposes of system administration, assisting in diagnosing problems with Hero servers, monitoring Hero's system performance and traffic on the Hero Properties and to gather broad demographic information about Hero Users.<br>- Personalization: Hero uses cookies and IP addresses to track features such as delivering Content specific to your interests and informing you of new, relevant services or certain third party offerings.<br>- Advertising: Hero may use Non-Personal Information to assist in optimizing the delivery of advertisements to viewers of your Content.</li>
        </ol>
        <p><b>HOW TO ACCESS, CHANGE AND ERASE YOUR PERSONAL INFORMATION</b><br>Upon request, Hero will allow Users to update or correct Personal Information previously submitted, but only to the extent such activities will not compromise privacy or security interests. Additionally, upon request, Hero will delete Personal Information from the database where such information is stored; however, it may be impossible to entirely delete a User’s entry without some residual information being retained due to the manner in which data backups are maintained. Requests to delete Personal Information may be submitted to <a href="mailto:support@markuphero.com" rel="noopener" target="_blank">support@markuphero.com</a>.</p>
        <p>Users also have the right to receive their Personal Information from us in a structured, commonly used and machine-readable format, and the right to transmit their Personal Information to another controller without hindrance from us (data portability).</p>
        <p><b>EMAIL PREFERENCES</b><br>Hero may use your Personal Information to send you emails periodically listing promotions or events relating to the Hero Properties. You have the choice to opt-out of receiving such promotional emails by sending an email to <a href="mailto:support@markuphero.com" rel="noopener" target="_blank">support@markuphero.com</a> and/or following the instructions in such correspondence. Once Hero's has processed your opt-out request, Hero will not send you promotional emails unless you opt back in to receiving such communications.</p>
        <p><b>DISCLOSURE OF INFORMATION TO THIRD PARTIES</b><br>Except as described below, we do not sell, transfer or otherwise disclose, sell, trade, or otherwise transfer your Personal Information to outside parties. This statement does not include trusted third party service providers who assist us in administering and providing the Hero Properties or provide services to us. Examples include storing and managed Content, analyzing data, providing marketing assistance, integrations of Third Party Services such as CRM and MAP services, processing credit card payments, and providing customer service. These third party service providers will have access to Personal Information needed to perform their functions, but may not use it for other purposes.</p>
        <p>We may use service providers located outside of the United States, and, if applicable, your Personal Information may be processed and stored in other countries and therefore may be subject to disclosure under the laws of those countries. You explicitly consent and agree to such transfer, storing and/or processing of your Personal Information outside of the United States or other country in which you are located.</p>
        <p>We may share Payment Information with third parties for purposes of fraud prevention or to process payment transactions.</p>
        <p>We may also release your information when we believe release is appropriate to comply with the law, enforce our policies, or protect our or others’ rights, property or for safety. We may also provide non-Personal Information to other parties for marketing, advertising or other uses.</p>
        <p>Information, including Personal Information, which we collect from Users and Viewers, is considered to be a business asset. As a result, in the unlikely event that we go out of business, enter bankruptcy or if we are acquired as a result of a transaction such as a merger, acquisition or asset sale, your Personal Information may be disclosed or transferred to the third-party acquirer in connection with the transaction.</p>
        <p>Lastly, we may provide Users with certain identifiable usage information directly related to the videos and/or other Content that they make available through the Hero Properties. Such information may include how many and which Content of a particular User was watched by a particular Viewer, from where a particular Content was watched by a particular Viewer and how many times a particular Content was watched by a particular Viewer. In addition, if you, as a Viewer, provide Personal Information (e.g. email address) as part of accessing and viewing Content, that Personal Information may be collected by us, a provider of Third Party Services or an Integrated Platform on behalf of the User who owns the Content and shared with that User or Third Party Service providers to that User, as we and others are their service provider. The use of such information will be subject to the information and privacy practices and policies of such Users and Hero will not be responsible or liable or the use of any information by such Users and any Hero will not be responsible for their use of your information.</p>
        <p>Under certain exceptional circumstances, Hero may have a legal duty or right to collect, use or disclose your Personal Information without your knowledge or consent. In accordance with applicable laws, We will not disclose any consumer information (which may include Personal Information) without your written consent, except where consumer information is required to be disclosed: (i) for billing or market operation purposes; (ii) for law enforcement purposes; or (iii) for the purpose of complying with a legal requirement.</p>
        <p>You are deemed to consent to disclosure of your information for the above purposes. If your Personal Information is shared with third parties other than Users, those third parties may be, but are not always, subject to appropriate agreements with Hero and/or its Users to secure and protect the confidentiality of your Personal Information.</p>
        <p><b>SAFEGUARDING YOUR PERSONAL INFORMATION</b><br>Hero takes appropriate security measures to protect against unauthorized access, alteration, disclosure or destruction of Personal Information. These include, but are not limited to, internal reviews of: (a) Hero's data collection; (b) storage and processing practices; (c) electronic security measures; and (d) physical security measures to guard against unauthorized access to systems where Hero stores Personal Information.</p>
        <p>Unfortunately, no data transmission over the internet can be guaranteed to be 100% secure. As a result, while we are committed to protecting your Personal Information, we cannot ensure or warrant the security of any information you provide to us.</p>
        <p>All Hero employees, contractors and agents who access Personal Information are bound by confidentiality obligations and may be subject to discipline, including termination and criminal prosecution or unauthorized use or disclosure of Personal Information.</p>
        <p>Some or all of the Personal Information we collect may be stored or processed on servers located outside your jurisdiction of residence, whose data protection laws may differ from the jurisdiction in which you live. As a result, this information may be subject to access requests from governments, courts, or law enforcement in those jurisdictions according to laws in those jurisdictions.</p>
        <p><b>RETENTION OF INFORMATION</b><br>Hero retains the Personal Information that we collect about you for as long as reasonably necessary for the purposes set out in this Privacy Policy. We also may retain your Personal Information for a longer period of time on the basis of our legitimate interests in providing or marketing our services to you or as necessary to comply with our legal obligations, to resolve disputes, and to enforce our agreements. Even if we delete some or all of your Personal Information, we may continue to retain and use information that has been aggregated or anonymized so that it can no longer be used for personal identification.</p>
        <p><b>CHILDREN AND STUDENTS</b><br>Hero takes the privacy of students and children extremely seriously. The Hero Services are not intended for children under 13 years of age. No one under age 13 may provide any information to or on the Hero Site. We do not knowingly collect Personal Information from children under 13. If you are under 13, do not use or provide any information on the Hero Site or via the Hero Services. If we learn we have collected or received Personal Information from a child under 13 without verification of parental consent, we will delete that information. If you believe we might have any information from or about a child under 13, please contact us at <a href="mailto:support@markuphero.com" rel="noopener" target="_blank">support@markuphero.com</a>.</p>
        <p>Hero is a signatory to the Student Privacy Pledge and has agreed to safeguard student privacy regarding the collection, maintenance, and use of student Personal Information. For more information, see <a href="https://studentprivacypledge.org" rel="noopener" target="_blank">https://studentprivacypledge.org</a>.</p>
        <p><b>EU AND SWISS PRIVACY SHIELD FRAMEWORKS</b><br>Hero complies with the EU-U.S. Privacy Shield Framework and the Swiss-U.S. Privacy Shield Framework as set forth by the U.S. Department of Commerce regarding the collection, use, and retention of Personal Information from European Union member countries (as well as Iceland, Liechtenstein, and Norway) and Switzerland transferred to the United States pursuant to the Privacy Shield. Hero has certified that it adheres to the Privacy Shield Principles with respect to such data. If there is any conflict between the policies in this Privacy Policy and data subject rights under the Privacy Shield Principles, the Privacy Shield Principles shall govern. To learn more about the Privacy Shield program, and to view our certification page, please visit <a href="http://www.privacyshield.gov" rel="noopener" target="_blank">http://www.privacyshield.gov</a>.</p>
        <p>With respect to Personal Information received or transferred pursuant to the Privacy Shield Frameworks, Hero is subject to the regulatory and enforcement powers of the U.S. Federal Trade Commission.</p>
        <p>Types of EU and Swiss Personal Data Collected. Our participation in the Privacy Shield applies to all Personal Information that is subject to this Privacy Policy and is received from the European Union and European Economic Area (“EU Personal Data”) and Switzerland (“Swiss Personal Data”). We will comply with the Privacy Shield Principles with respect to all EU and Swiss Personal Data. We may collect employment-related Personal Information regarding our employees located in the EU and Switzerland.</p>
        <p>Purposes of EU and Swiss Personal Data Collection and Use. We will only process EU and Swiss Personal Data in ways that are compatible with the purpose for which we collected the EU and Swiss Personal Data, or for purposes that the individual or entity providing the EU and Swiss Personal Data later authorizes.</p>
        <p>Pursuant to the Privacy Shield Frameworks, EU and Swiss individuals have the right to obtain our confirmation of whether we maintain Personal Information relating to you in the United States. Upon request, we will provide you with access to the Personal Information that we hold about you. You may also may correct, amend, or delete the Personal Information we hold about you. An individual who seeks access, or who seeks to correct, amend, or delete inaccurate data transferred to the United States under Privacy Shield, should direct their query to <a href="mailto:support@markuphero.com" rel="noopener" target="_blank">support@markuphero.com</a>. If requested to remove data, we will respond within a reasonable timeframe.</p>
        <p>We will provide an individual opt-out choice, or opt-in for sensitive data, before we share your data with third parties other than our agents, or before we use it for a purpose other than which it was originally collected or subsequently authorized. To request to limit the use and disclosure of your Personal Information, please submit a written request to <a href="mailto:support@markuphero.com" rel="noopener" target="_blank">support@markuphero.com</a>.</p>
        <p>In certain situations, we may be required to disclose Personal Information in response to lawful requests by public authorities, including to meet national security or law enforcement requirements.</p>
        <p>Hero’s accountability for Personal Information that it receives in the United States under the Privacy Shield and subsequently transfers to a third party is described in the Privacy Shield Principles. In particular, Hero remains responsible and liable under the Privacy Shield Principles if third-party agents that it engages to process the Personal Information on its behalf do so in a manner inconsistent with the Principles, unless Hero proves that it is not responsible for the event giving rise to the damage.</p>
        <p>In compliance with the Privacy Shield Principles, Hero commits to resolve complaints about your privacy and our collection or use of your Personal Information transferred to the United States pursuant to Privacy Shield. European Union and Swiss individuals with Privacy Shield inquiries or complaints should first contact Hero by email at <a href="mailto:support@markuphero.com" rel="noopener" target="_blank">support@markuphero.com</a> or via post at:</p>
        <p><b>HERO, Inc.</b><br>9415 Culver Blvd. <br>Suite #186<br>Culver City, CA 90232</p>
        <p>Hero has further committed to refer unresolved privacy complaints under the Privacy Shield Principles to an independent dispute resolution mechanism, the BBB EU PRIVACY SHIELD, operated by the Council of Better Business Bureaus. If you do not receive timely acknowledgment of your complaint, or if your complaint is not satisfactorily addressed, please visit <a href="http://www.bbb.org/EU-privacy-shield/for-eu-consumers" rel="noopener" target="_blank">www.bbb.org/EU-privacy-shield/for-eu-consumers</a> for more information and to file a complaint. This service is provided free of charge to you.</p>
        <p>Hero commits to cooperate with the EU data protection authorities (DPAs) and the Swiss Federal Data Protection and Information Commissioner (FDPIC) and comply with the advice given by such authorities with regard to human resources data transferred from the EU and/or Switzerland, as applicable, in the context of the employment relationship with Hero.</p>
        <p>If your Privacy Shield complaint cannot be resolved through the above channels, under certain conditions, you may invoke binding arbitration for some residual claims not resolved by other redress mechanisms. See Privacy Shield Annex 1 at <a href="https://www.privacyshield.gov/article?id=ANNEX-I-introduction" rel="noopener" target="_blank">https://www.privacyshield.gov/article?id=ANNEX-I-introduction</a>.</p>
        <p><b>THIRD PARTY WEBSITES AND SERVICES</b><br>The Hero Properties may contain links to third party websites or services, including Third Party Services, (collectively, “Third Party Sources”) who may collect Personal Information and Non-Personal Information directly from you. Links to Third Party Sources are intended for convenience only. Third Party Sources are wholly independent from Hero. Third Party Source may have separate privacy policies and data collection practices, independent of Hero. Hero: (a) has no responsibility or liability for these independent policies or actions; (b) is not responsible for the privacy practices or the content of such websites; and (c) does not make any warranties or representations about the contents, products or services offered on such websites or the security of any information you provide to them.</p>
        <p><b>CHANGES TO THIS PRIVACY POLICY</b><br>The terms in this Privacy Policy may be changed from time to time, so you should review it periodically for changes. We reserve the right, at any time, to modify or replace this Privacy Policy. The date of the most recent version of the Privacy Policy is noted below under “Effective Date of this Privacy Policy.” We may also notify you via email or other direct electronic communication method of any changes that, in our sole discretion, materially impact your use of the Hero Properties or the treatment of your Personal Information. Your use of the Hero Properties following the posting of any changes to the Privacy Policy constitutes acceptance of those changes.</p>
        <p>HOW TO CONTACT US<br>If you have any questions or concerns about this Privacy Policy or our privacy practices, you may contact us directly as follows:</p>
        <p>Email us: <a href="mailto:support@markuphero.com" rel="noopener" target="_blank">support@markuphero.com</a>.</p>
        <p>or:</p>
        <p><b>HERO, Inc.</b><br>9415 Culver Blvd. <br>Suite #186<br>Culver City, CA 90232</p>
        <p>If you are a resident of the European Union, and you believe that our processing of your Personal Information is inconsistent with your data protection rights under the GDPR and we have not adequately addressed your concerns, you have the right to lodge a complaint with the data protection supervisory authority of your country. <a href="http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.html" rel="noopener" target="_blank">http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.html</a></p>
      </article>
    </div>
    <Footer></Footer>
  </div>
</template>

<script>
  import Nav from "./Nav";
  import Footer from "./Footer";
  export default {
    name: "Privacy",
    components: {Nav, Footer},
    methods: {
      async redirectToPrivacy() {
        await this.$router.push('/privacy');
      }
    }
  }
</script>

<style scoped>
  div.container {
    margin: 120px auto;
    padding: 0 40px;
    max-width: 640px;
    color: #fff;
  }

  article {
    font-size: 16px;
    line-height: 25px;
  }

  label {
    color: #9ca5b4;
  }

  a {
    color: #fff;
  }

  @media screen and (max-width: 479px) {
    div.container {
      padding: 0 20px;
    }
  }
</style>