<template>
  <div>
    <Nav></Nav>
    <div class="container">
      <h1>Terms of Service</h1>
      <label>Updated August 18, 2020</label>
      <article>
        <p>These Terms of Service (these “Terms”) govern your use of the Hero website (the “Site”), the Hero video platform and associated tools (collectively, the “Service”) made available by Hero, Inc. (“Hero”, "our", "us", or "we"). Your use of the Site and/or your registration to use the Service indicates that you agree on behalf of yourself or the entity that you represent (collectively, "you") to be bound by these Terms as well as the Hero <a href="/privacy" v-on:click.prevent="redirectToPrivacy()"><b>Privacy Policy</b></a>. Please read these Terms carefully before registering for or otherwise using the Hero Service.</p>
        <p><b>I. Overview </b><br>Hero provides a content markup and annotation platform. Hero is offered via the following plans or service offerings.‍</p>
        <ol>
          <li>
            <i>Sidekick Plan</i>. For individuals that want to try risk free without an account.</li>
          <li>
            <i>Hero Plan</i>. For individuals that want the basic tools and features with history for 30 markups per month.</li>
          <li>
            <i>Superhero Plan</i>. For professionals that need access to all our tools and features with unlimited usage.</li>
          <li>
            <i>Superhero Enterprise Plan</i> (coming soon).</li>
        </ol>
        <p>See our Site for further details on the features of the various Hero Service offerings, which Hero will endeavor to improve and expand over time. By registering for a Hero Team or Hero Company account, you acknowledge that the account administrator of your organization has control of and access to Your Content (as defined below). Furthermore, you (1) agree to comply with your organization’s terms and policies with regard to your use of the Service; (2) acknowledge your organization’s ability to monitor, restrict or terminate your or other users’ access to Your Content; and (3) acknowledge your organization’s ownership of the Hero Team or Hero Company account.</p>
        <p><b>II. Registration</b> <br>Use of the Service does not require that you register with Hero. However, some features do require creation of an account. When you register with Hero, you will be asked to disclose certain personal information, including email address, and to set up a password, all of which will be subject to our <a href="/privacy" v-on:click.prevent="redirectToPrivacy()"><b>Privacy Policy</b></a>. You are responsible for all activities that occur under your account and for keeping your password and log-in information secure. You agree that you (1) will monitor your account, (2) will not share your account or password with anyone, and (3) will notify Hero immediately of any unauthorized use of your account or password, or any other breach of security. You agree to provide us with true, accurate and complete information as requested in our registration process. You also agree to update such information promptly as necessary to keep it current and accurate.</p>
        <p><b>III. Payment</b> <br>If you register for Superhero or Superhero Enterprise (collectively, “Hero Premium”), you agree to pay all fees or charges to your account for the Service in accordance with the fees, charges and billing terms in effect at the time that each fee or charge is due and payable. Unless otherwise indicated in an order form, you must provide Hero with a valid credit card (Visa, MasterCard, or any other issuer accepted by us) (“Payment Provider”) as a condition to signing up for the Hero Premium. Your Payment Provider agreement governs your use of the designated credit card account, and you must refer to that agreement and not these Terms to determine your rights and liabilities with respect to your Payment Provider. By providing Hero with your credit card number and associated payment information, you agree that Hero is authorized to verify information immediately, and subsequently invoice your account for all fees and charges due and payable to Hero hereunder and that no additional notice or consent is required. You agree to immediately notify Hero of any change in your billing address or the credit card used for payment hereunder. Hero reserves the right at any time to change its prices and billing methods, either immediately upon posting on our Site or by e-mail delivery to your organization’s administrator(s).</p>
        <p>Any attorney fees, court costs, or other costs incurred in collection of delinquent undisputed amounts shall be the responsibility of and paid for by you.</p>
        <p>All fees for the Service are non-refundable. No contract will exist between you and Hero for the Service until Hero accepts your order by a confirmatory e-mail, SMS/MMS message, or other appropriate means of communication.</p>
        <p>You are responsible for any third-party fees that you may incur when using the Service.</p>
        <p><b>IV. Changes to and Your Termination of the Service</b> <br>You acknowledge and agree that Hero may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at Hero’s sole discretion, without prior notice to you (except that if you are a Hero Premium customer, Hero will notify you and not charge you for any Service that you have not received). You may stop using the Service at any time. You do not need to specifically inform Hero when you stop using the Service. You acknowledge and agree that if Hero disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.<br><br><b>V. User Conduct, Commitments and Understandings<br></b>You agree not to access (or attempt to access) any of the Service by any means other than through the interface that is provided by Hero, unless you have been specifically allowed to do so in a separate agreement with Hero.</p>
        <p>You, directly or indirectly, alone or with any other party, may not:</p>
        <ol>
          <li>modify, change, create derivative works of, disassemble, decompile or otherwise reverse engineer the Service or any software provided in connection with the Service (“Software”), or remove proprietary legends in the Service or Software;</li>
          <li>distribute, transfer, resell, rent, lease, or loan the Service or Software to any other party, except as described herein;</li>
          <li>make the Service or Software available to others in a service bureau arrangement or for any similar commercial time-sharing or third party training use;</li>
          <li>harass, threaten or otherwise cause distress, unwanted attention or discomfort to a person or entity;</li>
          <li>post or otherwise transmit any unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or hateful content or content which is racially, ethnically or otherwise objectionable, or which infringes upon the rights of any third party;</li>
          <li>post or otherwise transmit any content that (i) infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party; (ii) you do not have the right to transmit, such as information that is subject to a confidentiality agreement between you and another party; (iii) contains sexually explicit images or other content that is offensive; (iv) is harmful to minors in any way; or (v) promotes or provides instructional information about illegal activities or promotes physical harm or injury against any group or individual;</li>
          <li>send any unsolicited commercial email, spam, or bulk commercial email;</li>
          <li>impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
          <li>\violate (intentionally or unintentionally) any applicable local, state, national or international law including, but not limited to, any regulations having the force of law; or</li>
          <li>interfere with or disrupt the Service or Software, or servers or networks connected to the Software, or disobey any requirements, procedures, policies or regulations of networks connected to the Service or Software.</li>
        </ol>
        <p>You agree that you are solely responsible for (and that Hero has no responsibility to you or to any third party for) any breach of your obligations under these Terms and for the consequences (including any loss or damage which Hero may suffer) of any such breach. To the extent Hero incurs any financial penalties or other costs and expenses (including investigation expenses) from Hero’s server hosting facility, internet service provider or other vendors because of your use of the Software, you shall be obligated to immediately reimburse Hero for any such penalties, costs or expenses.</p>
        <p>You understand that all information (such as data files, written text, computer software, music, audio files or other sounds, photographs, videos or other images) which you may have access to as part of, or through your use of, the Service are the sole responsibility of the person from which such materials originated, which may be you.</p>
        <p>While Hero uses reasonable efforts to include accurate and up-to-date information on the Site, Hero makes no warranties or representations as to its accuracy. Hero assumes no liability or responsibility for any errors or representations in the content available on the Site (the “Content”).</p>
        <p>The Site may contain links to other sites on the Internet which are owned and operated by Third Party Vendors and other third parties (the “External Sites”). You acknowledge that Hero is not responsible for the availability of, or the materials located on or through, any External Sites. You should contact the site administrator or webmaster for those External Sites if you have any concerns regarding such links or the materials located on such External Sites.</p>
        <p>You acknowledge that by accessing the Site, you may come into contact with Content that you find harmful, offensive, threatening, indecent or objectionable and you acknowledge that Hero shall have no liability to you for the Content including, but not limited to explicit language and other potentially offensive material. You agree not to impersonate any person or communicate under a false name or a name you are not entitled or authorized to use. Hero has the right (but not the obligation) to remove, prohibit, edit or discontinue any Content on the Site, including Content that has been posted by users.</p>
        <p>You retain sole ownership of any Content you post or any other material you submit using the Service (“Your Content”). You hereby grant Hero and its affiliates a revocable, worldwide, royalty-free, non-exclusive, sublicensable license to use, reproduce and display Your Content solely for the purpose of providing the Service to you. Hero will not use Your Content for any other purpose or distribute Your Content to any third party without your permission. You represent and warrant that Your Content will be your original work product and will not be based on, or derived from, the proprietary information or materials of a third party. Furthermore, you represent and warrant that your use of the Service in connection with Your Content or any third party content complies with all laws including, but not limited to, copyright law. You also hereby grant each user of the Service a non-exclusive license to access Your Content through the Service. The licenses granted in Your Content terminate within a commercially reasonable time after you remove or delete Your Content from the Service; however, you understand, acknowledge and agree that Hero may retain, but not display, server copies of Your Content that has been removed or deleted. You grant Hero and its affiliates a perpetual and irrevocable license to use and display any comments you add via the Service. You will defend, indemnify and hold Hero and its affiliates harmless from and against any claims resulting from any of Your Content.</p>
        <p>At your discretion, you may provide feedback to Hero concerning the functionality and performance of the Service from time to time, including, without limitation, identifying potential errors, improvements, modifications, bug fixes, or enhancements (“Feedback”). If you, through your evaluation or otherwise, suggests any Feedback, you hereby assign the ownership in all Feedback to Hero. In the event ownership in the Feedback cannot be granted to Hero, you grant Hero at no charge a perpetual, irrevocable, royalty-free, worldwide right and license to use, reproduce, disclose, sublicense, distribute, modify, and otherwise exploit such Feedback without restriction. You agree that Hero may disclose that Feedback to any third party in any manner and you agree that Hero has the ability to sublicense all Feedback in any form to any third party without restriction.</p>
        <p>The Site may contain areas in which additional terms and conditions apply. For purposes of the use of such areas, in the event of a conflict between the terms and conditions of such other areas and these Terms, the terms and conditions of the other area shall prevail. Hero may at any time revise these Terms by updating this posting. You are bound by any such revisions and should therefore periodically visit this page to review the current Terms to which you are bound.</p>
        <p>You shall not transmit to Hero or upload to this Site any Harmful Code or use or misappropriate the data on this Site for your own commercial gain. “Harmful Code” shall mean any software (sometimes referred to as “viruses,” “worms,” “trojan horses,” “time bombs,” “time locks,” “drop dead devices,” “traps,” “access codes,” “cancelbots” or “trap door devices”) that: (a) is intentionally designed to damage, disrupt, disable, harm, impair, interfere with, intercept, expropriate or otherwise impede in any manner, any data, storage media, program, system, equipment or communication, based on any event, including for example but not limited to (i) exceeding a number of copies, (ii) exceeding a number of users, (iii) passage of a period of time, (iv) advancement to a particular date or other numeral, or (v) use of a certain feature; or (b) would enable an unauthorized person to cause such result; or (c) would enable an unauthorized person to access another person’s information without such other person’s knowledge and permission.</p>
        <p>You may not use your username and password for any unauthorized purpose.</p>
        <p><b>VI. Monitoring and Enforcement; Termination</b> <br>Hero has the right to:</p>
        <ol>
          <li>Remove or refuse to post any of Your Content for any or no reason in our sole discretion. - Take any action with respect to Your Content that we deem necessary or appropriate in our sole discretion, including if we believe that Your Content violates these Terms, infringes any intellectual property right or other right of any person or entity, threatens the personal safety of users of the Service or the public or could create liability for Hero.</li>
          <li>Take appropriate legal action, including without limitation, referral to law enforcement, for any illegal or unauthorized use of the Service or the Site.</li>
          <li>Terminate or suspend your access to all or part of the Service or the Site for any violation of these Terms.</li>
        </ol>
        <p>Without limiting the foregoing, we have the right to fully cooperate with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone posting any materials on or through the Service or the Site. YOU WAIVE AND HOLD HARMLESS HERO AND ITS AFFILIATES, LICENSEES AND SERVICE PROVIDERS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY ANY OF THE FOREGOING PARTIES DURING OR AS A RESULT OF ITS INVESTIGATIONS AND FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER SUCH PARTIES OR LAW ENFORCEMENT AUTHORITIES.</p>
        <p>However, we do not undertake to review Content before it is posted via the Service, and we cannot ensure prompt removal of objectionable material after it has been posted. Accordingly, we assume no liability for any action or inaction regarding transmissions, communications or Content provided by any user or third party. We have no liability or responsibility to anyone for performance or nonperformance of the activities described in this section.</p>
        <p><b>VII. Indemnity</b> <br>You agree to indemnify, defend and hold harmless Hero, and its directors, officers, agents, contractors, partners and employees, from and against any loss, liability, claim, demand, damages, costs and expenses (including reasonable attorney's fees) arising out of or in connection with (i) any allegation that any of Your Content infringes or misappropriates any intellectual property or other proprietary right of a third party or violates any applicable law, (ii) your conduct in connection with the Service, and/or (iii) any violation by you of these Terms.</p>
        <p><b>VIII. Intellectual Property Rights</b> <br>Hero reserves all rights not specifically granted herein. You shall not modify any copyright notices, proprietary legends, any trademark and service mark attributions, any patent markings, and other indicia of ownership on the Content or other materials accessed through the Service. The delivery of, and license to, the Content and/or access to third party materials does not transfer to you any commercial or promotional use rights in the Content or any portion thereof. Any use of Content, or descriptions; any derivative use of this Site or its materials; and any use of data mining, robots, or similar data gathering and extraction tools is strictly prohibited. In no event shall the user frame any portion of the Site or any materials contained therein.</p>
        <p>As between the parties, Hero owns and shall continue to own all right, title and interest in and to all aggregate and statistical information or analyses created and developed by Hero from performance and usage data generated through your use of the Site, Service or Software (collectively, “Aggregate Data”). Aggregate Data is de-identified so that you cannot be identified as the source within the Aggregate Data.</p>
        <p><b>IX. Copyright Protection</b> <br>The U.S. Digital Millennium Copyright Act ("DMCA") provides recourse to copyright owners who believe that their rights under the United States Copyright Act have been infringed by acts of third parties over the Internet. If you believe that any content uploaded or otherwise made available on the Service infringes upon any copyright which you own or control, you may so notify us in accordance with our DMCA process available <a href="https://markuphero.com/copyright" rel="noopener" target="_blank"><b>here</b></a>. In accordance with the DMCA and other applicable law, we have adopted a policy of terminating, in appropriate circumstances and at our sole discretion, the accounts of users of the Service who are deemed to be repeat infringers. Hero may also at its sole discretion limit access to the Service or terminate the account of any user who infringes any intellectual property rights of others, whether or not there is any repeat infringement.‍</p>
        <p><b>X. [intentionally removed]</b></p>
        <p><b>XI. Governing Law</b> <br>Your use of the Service and these Terms shall be governed by, and construed in accordance with, the internal laws of the State of California without reference to the choice of law or conflicts of law principles thereof, and all claims relating to or arising out of your use of the Service or these Terms, or the breach thereof, whether sounding in contract, tort or otherwise, shall likewise be governed by the laws of the State of California without reference to the choice of law or conflicts of law principles thereof.</p>
        <p><b>XII. Disclaimer of Warranties</b> <br>THE MATERIALS, CONTENT ON THIS SITE AND SERVICE ARE PROVIDED “AS IS”, “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. HERO SHALL HAVE NO RESPONSIBILITY OR LIABILITY FOR ANY CONTENT, MATERIALS POSTED ON THE SITE OR SERVICES. HERO MAKES NO GUARANTEES AS TO UPTIME OR AVAILABILITY OF THE SERVICE. TO THE FULLEST EXTENT POSSIBLE PURSUANT TO THE APPLICABLE LAW, HERO DISCLAIMS ALL WARRANTIES, EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT OR OTHER VIOLATION OF RIGHTS. THE SERVICE MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS. LOON IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS, INCLUDING INTERNET CONGESTION, VIRUS ATTACKS, AND DENIAL OF SERVICE (DOS) ATTACKS.</p>
        <p><b>XIII. Limitation of Liability</b> <br>UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, BREACH OF CONTRACT, OR BREACH OF ANY STATUTORY OR OTHER DUTY OF CARE, SHALL HERO OR ITS THIRD PARTY LICENSORS BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES, INCLUDING, BUT NOT LIMITED TO, LOSS OF DATA OR PROFIT, ARISING OUT OF THE USE, OR THE INABILITY TO USE, THE MATERIALS ON THIS SITE OR THE SERVICE, EVEN IF HERO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY REMEDY.</p>
        <p>HERO’S AND ITS LICENSORS’ ENTIRE AND AGGREGATE LIABILITY, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, SHALL NOT EXCEED THE GREATER OF $100 OR THE AMOUNT YOU HAVE PAID TO HERO FOR THE SERVICE DURING THE SIX (6) MONTHS PRECEDING THE DATE THAT A CLAIM OR DEMAND IS FIRST ASSERTED, EVEN IF HERO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY REMEDY. IF YOUR USE OF MATERIALS FROM THIS SITE OR THE SERVICE RESULTS IN THE NEED FOR SERVICING, REPAIR OR CORRECTION OF EQUIPMENT OR DATA, YOU ASSUME ANY COSTS THEREOF. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.</p>
        <p><b>XIV. Entire Agreement; Modifications</b> <br>These Terms constitute the entire agreement between the parties regarding the subject matter hereof and supersede all proposals and prior discussions and writings between the parties with respect thereto. No failure or delay in enforcing any right or exercising any remedy will be deemed a waiver of any right or remedy. Each provision of these Terms is a separately enforceable provision. If any provision of these Terms is determined to be or becomes unenforceable or illegal, such provision shall be reformed to the minimum extent necessary in order for these Terms to remain in effect in accordance with its terms as modified by such reformation. These Terms may not be modified, supplemented, amended or interpreted by any trade usage or prior course of dealing unless specifically agreed upon in writing. Reasonable attorneys’ fees and costs will be awarded to the prevailing party in the event of litigation involving the enforcement or interpretation of these Terms.</p>
        <p><b>XV. Force Majeure</b> <br>Hero shall not be liable to you for any delay or failure of Hero to perform its obligations hereunder if such delay or failure arises from any cause or causes beyond the reasonable control of Hero. Such causes shall include, but are not limited to, acts of God, floods, fires, loss of electricity or other utilities, labor strike, or delays by you in performing any requirements hereunder.</p>
        <p><b>XVI. Dispute Resolution</b> <br>The state or federal courts sitting in Los Angeles County, California shall have exclusive jurisdiction and venue over any dispute arising out of these Terms and sale, and you hereby consent to the jurisdiction of such courts. Any dispute, controversy or claim arising under, out of or relating to these Terms and any subsequent amendments of these Terms, including, without limitation, its formation, validity, binding effect, interpretation, performance, breach or termination, as well as non-contractual claims, shall be submitted to arbitration before the American Arbitration Association (“AAA”) in accordance with the AAA Commercial Arbitration Rules. The place of arbitration shall be Los Angeles, California. The language to be used in the arbitral proceedings shall be English. The parties may apply to any court of competent jurisdiction for a temporary restraining order, preliminary injunction, or other interim or conservatory relief as necessary, without breach of this Section and without abridgment of the powers of the arbitrator. The arbitrator may award any form of individual or equitable relief, including injunctive relief. Any award will be final and conclusive to the parties and may be entered in any court of competent jurisdiction. You agree to the entry of injunctive relief to stop any lawsuit or to remove you as a participant in such a suit. These Terms do not constitute a waiver of any of your rights and remedies to pursue a claim individually in binding arbitration, but not as a class action. This provision preventing you from bringing, joining or participating in any class action lawsuits is an independent covenant. You may opt-out of this Section by providing written notice of your decision within thirty (30) days of the date that you first use the Site or Service.</p>
        <p><b>XVII. Questions and Comments</b> If you have any questions regarding these Terms, please contact Hero by emailing <a href="mailto:support@markuphero.com" rel="noopener" target="_blank"><b>support@markuphero.com</b>.</a></p>
        <p><b>XVIII. Notices</b> All notices regarding these Terms and the Service will be provided in writing to you by e-mail using the contact information provided by you upon registration or by posting on the Site. Notice will be deemed given one (1) business day after e-mail transmission from Hero, or two (2) business days after the date of posting.</p>
      </article>
    </div>
    <Footer></Footer>
  </div>
</template>

<script>
  import Nav from "./Nav";
  import Footer from "./Footer";
  export default {
    name: "Terms",
    components: {Nav, Footer},
    methods: {
      async redirectToPrivacy() {
        await this.$router.push('/privacy');
      }
    }
  }
</script>

<style scoped>
  div.container {
    margin: 120px auto;
    padding: 0 40px;
    max-width: 640px;
    color: #fff;
  }

  article {
    font-size: 16px;
    line-height: 25px;
  }

  label {
    color: #9ca5b4;
  }

  a {
    color: #fff;
  }

  @media screen and (max-width: 479px) {
    div.container {
      padding: 0 20px;
    }
  }
</style>